version: '3.8'

networks:
  posttest-run:

services:
  db:
    image: postgres:16.0
    environment:
      POSTGRES_USER: adminpg
      POSTGRES_PASSWORD: pg@admin
      POSTGRES_DB: lotterydb
    restart: on-failure
    ports:
      - "5431:5432"
    volumes:
      - ./db:/docker-entrypoint-initdb.d/
    networks:
      - posttest-run