version: '3.8'

networks:
  posttest-run:

services:
  api-backend:
    container_name: posttest-api-backend
    build:
      context: .
      dockerfile: Dockerfile
    image: posttest-api-backend
    ports:
      - "8888:8888"
    depends_on:
      - db
    networks:
      - posttest-run
    environment:
      SPRING_DATASOURCE_URL: ${DATABASE_URL}
      SPRING_DATASOURCE_USERNAME: ${DATABASE_USER}
      SPRING_DATASOURCE_PASSWORD: ${DATABASE_PASS}

  db:
    image: postgres:16.0
    environment:
      POSTGRES_USER: adminpg
      POSTGRES_PASSWORD: pg@admin
      POSTGRES_DB: lotterydb
    restart: on-failure
    ports:
      - "5432:5432"
    volumes:
      - ./db:/docker-entrypoint-initdb.d/
    networks:
      - posttest-run